version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      -postgres_data:/var/lib/postgres/postgres_data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@Dear2456
      - POSTGRES_DB=database.py
    ports:
      -"5432:5432"
  volumes:
    -postgres_data: