version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      -postgres_data:/var/lib/postgres/postgres_data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=apartment_db
    ports:
      -"5432:5432"
  volumes:
    -postgres_data: